version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    networks:
      - app-network

  # Add your backend service here when ready
  # backend:
  #   build: ./backend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge 